---
date: "`r format(Sys.time(), '%d de %B de %Y')`"
fontsize: "10pt"
output: 
  beamer_presentation: 
    fig_caption: yes
    highlight: zenburn
    includes:
      in_header: preambulo-beamer.tex
    keep_tex: yes
    slide_level: 3
---

###  ###

\titlepage

### Sumário ###

\tableofcontents[hideallsubsections]

<!-- ------------------------------------------- -->
# Introdução #

## Modelos de regressão ##

###  ###

## Modelos para dados de contagem ##

###  ###

## Distribuição COM-Poisson ##

###  ###

## Modelo de regressão COM-Poisson ##

###  ###

## Extensões do modelo de regressão COM-Poisson ##

###  ###

<!-- ------------------------------------------- -->
# Objetivos #

###  ###

<!-- ------------------------------------------- -->
# Materiais e Métodos #

## Resursos Computacionais ##

###  ###

## Conjunto de dados ##

###  ###

## Estimação por máxima verossimilhança ##

###  ###

## Critérios para Comparação ##

###  ###

<!-- ------------------------------------------- -->
# Cronograma #

###  ###

\begin{figure}
\centering
\hspace{-0.5cm}
\begin{tikzpicture}[thick, scale=0.75, every node/.style={scale=0.75}]
\begin{ganttchart}[
canvas/.append style={fill=none},
y unit title=0.5cm, % Size da indicação do tempo
y unit chart=0.7cm, % Size do altura das colunas
x unit= 5.8mm, % largura das celulas
vgrid={*1{black!50, dotted}}, % grid cinza vertical
hgrid={*1{black!50, dotted}}, % grid cinza horizontal
title height=1, % Size dos dias
bar/.style={fill=done, draw=teal},
bar incomplete/.append style={fill=gray!10, draw=teal}, 
bar label node/.append style={align=right},
bar label font=\scriptsize\color{black!65},
group label font=\bfseries\scriptsize\color{black},
group left peak width=0.2,
group right peak width=0.2,
group left peak height=0.15,
group right peak height=0.15,
group left shift=.1, group right shift=-.1,
bar height=0.6, % size das barras de tarefas
bar left shift=.2, bar right shift=-.2,
bar top shift=.1, bar height=.8,
link/.style={-to, line width=0.7pt, black!50},
link type=dr
]{1}{24} % 
%\gantttitle{\color{teal}\bf Cronograma de atividades para 2016}{24}\\
\gantttitle{Fevereiro}{4}
\gantttitle{Março}{4} 
\gantttitle{Abril}{4} 
\gantttitle{Maio}{4} 
\gantttitle{Junho}{4} 
\gantttitle{Julho}{4} \\
%\gantttitlelist{1,...,24}{1} \\
\ganttgroup[group label node/.append style={align=right}, 
progress=75]{Projeto \ganttalignnewline de Pesquisa}{1}{3} \\
\ganttbar[progress=80]{Redação da \ganttalignnewline versão 
final}{1}{2} \\
\ganttbar[progress=0, progress label text=]{Entrega à
\ganttalignnewline banca}{3}{3} \\
\ganttgroup[group label node/.append style={align=right},
progress=15]{Elaboração \ganttalignnewline da Pesquisa}{2}{20} \\
\ganttbar[progress=40]{Revisão de \ganttalignnewline
literatura}{2}{8} \\
\ganttbar[progress=10]{Implementação
\ganttalignnewline Computacional}{7}{14} \\
\ganttbar[progress=0, progress label text= ]{Análise
\ganttalignnewline dos dados}{11}{14} \\
\ganttbar[progress=0, progress label text= ]{Discussão
\ganttalignnewline dos resultados}{13}{16} \\
\ganttbar[progress=0, progress label text= ]{Redação
\ganttalignnewline da pesquisa}{15}{20} \\
\ganttgroup[group label node/.append style={align=right},
progress=0, progress label text=]{Defesa \ganttalignnewline do
Trabalho}{20}{21} \\  
\ganttbar[progress=0, progress label text= ]{Elaboração da
\ganttalignnewline apresentação}{20}{20} \\
\ganttgroup[group label node/.append style={align=right},
progress=0, progress label text=]{Revisão Final}{21}{24} \\ 
\ganttbar[progress=0, progress label text= ]{Incorporação
\ganttalignnewline das sugestões}{21}{22} \\
\ganttbar[progress=0, progress label text= ]{Redação da 
\ganttalignnewline versão final}{22}{23}
 \ganttlink{elem1}{elem2}
 \ganttlink{elem1}{elem3}
 \ganttlink{elem4}{elem5}
 \ganttlink{elem4}{elem7}
 \ganttlink{elem4}{elem8}
 \ganttlink{elem5}{elem6}
 \ganttlink{elem5}{elem7}
 \ganttlink{elem8}{elem10}
 \ganttlink{elem10}{elem12}
 \ganttlink{elem10}{elem13}
 \ganttlink{elem12}{elem13}
\end{ganttchart}
\end{tikzpicture}
\caption{Cronograma de atividades para 2016}
\end{figure}
